# Baseline results

In [10]:
import os
import random
import warnings
from dotenv import load_dotenv
from rich import pretty, print, traceback
from tqdm import tqdm

warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=FutureWarning)
traceback.install(show_locals=True)
pretty.install()
load_dotenv();

In [11]:
positive_class = "Pneumonia"

## Load model

In [12]:
from model_chexagent.chexagent import CheXagent
chexagent = CheXagent()

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Loading checkpoint shards: 100%|██████████| 3/3 [00:03<00:00,  1.00s/it]

## Load dataset

In [13]:
from datasets import load_dataset, Dataset
ds: Dataset = load_dataset("vllm-pneumonia-detection/mimic-500-gt", split="test")
image_root_path = "/home/nicoleg/physionet.org/files/mimic-cxr-jpg/2.0.0/"

def in_domain(sample):
    label = sample[positive_class]
    return label == 0 or label == 1

def set_image_path(sample):
    sample["image_files"] = image_root_path + sample["image_files"]
    return sample

ds = ds.filter(in_domain)
ds = ds.map(set_image_path)

In [14]:
sample = random.choice(ds)
print(sample)

{
    'dicom_id': '99a719f1-338c19ff-4c6100c3-a98e761a-254572ee',
    'split': 'test',
    'study_id': '58245185',
    'subject_id': '17720924',
    'image_files':
'/home/nicoleg/physionet.org/files/mimic-cxr-jpg/2.0.0/files/p17/p17720924/s58245185/99a719f1-338c19ff-4c6100c3-a98
e761a-254572ee.jpg',
    'reports': '                                 FINAL REPORT\n CHEST RADIOGRAPH\n \n TECHNIQUE:  PA and lateral
chest views were reviewed in comparison with prior\n chest radiographs with the most recent from ___.\n \n
FINDINGS:  Lungs are clear. No evidence of pulmonary edema or pneumonia. Focal\n opacity over anatomical region of
lingula which is perceived only on frontal\n view represents a pericardial fat.  Heart size, mediastinal and hilar
contours\n are normal.  There is no pleural effusion or pneumothorax.  \n \n IMPRESSION; No pulmonary edema\n',
    'Atelectasis': -2.0,
    'Cardiomegaly': 0.0,
    'Consolidation': -2.0,
    'Edema': 0.0,
    'Enlarged Cardiomediastinum': 0.0,
    'Fracture': -2.0,
    'Lung Lesion': -2.0,
    'Lung Opacity': -2.0,
    'No Finding': -2.0,
    'Effusion': 0.0,
    'Pleural Other': -2.0,
    'Pneumonia': 0.0,
    'Pneumothorax': 0.0,
    'Support Devices': -2.0
}

# Get results

In [15]:
def get_response_with_report(paths: list, report: str) -> str:
    prompt = f'{report.strip()}\nDoes this chest X-ray contain a {positive_class}?'
    response = chexagent.generate(paths, prompt)
    return response

results = {}
yes_no = {"yes": 1, "no": 0}
for sample in tqdm(ds.shuffle(seed=42)):
    dicom_id = sample["dicom_id"]
    path = sample["image_files"]
    report = sample["reports"]
    response = get_response_with_report([path], report).lower()
    ypred = yes_no[response]
    results[dicom_id] = {
        "y_true": sample[positive_class],
        "y_pred": ypred,
        "image_files": path,
    }

  0%|          | 0/89 [00:00<?, ?it/s]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

  1%|          | 1/89 [00:01<02:40,  1.83s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  2%|▏         | 2/89 [00:03<02:14,  1.55s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  3%|▎         | 3/89 [00:04<02:09,  1.50s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  4%|▍         | 4/89 [00:05<02:00,  1.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  6%|▌         | 5/89 [00:07<01:55,  1.37s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  7%|▋         | 6/89 [00:08<01:53,  1.36s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  8%|▊         | 7/89 [00:09<01:52,  1.37s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
  9%|▉         | 8/89 [00:11<01:50,  1.36s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 10%|█         | 9/89 [00:12<01:48,  1.35s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 11%|█         | 10/89 [00:13<01:47,  1.36s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 12%|█▏        | 11/89 [00:15<01:45,  1.35s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 13%|█▎        | 12/89 [00:16<01:44,  1.36s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 15%|█▍        | 13/89 [00:18<01:45,  1.39s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 16%|█▌        | 14/89 [00:19<01:42,  1.36s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 17%|█▋        | 15/89 [00:20<01:40,  1.36s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 18%|█▊        | 16/89 [00:22<01:38,  1.34s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 19%|█▉        | 17/89 [00:23<01:38,  1.37s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 20%|██        | 18/89 [00:25<01:40,  1.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 21%|██▏       | 19/89 [00:26<01:35,  1.37s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 22%|██▏       | 20/89 [00:27<01:33,  1.36s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 24%|██▎       | 21/89 [00:28<01:32,  1.35s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 25%|██▍       | 22/89 [00:30<01:32,  1.38s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 26%|██▌       | 23/89 [00:31<01:30,  1.37s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 27%|██▋       | 24/89 [00:33<01:28,  1.36s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 28%|██▊       | 25/89 [00:34<01:31,  1.43s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 29%|██▉       | 26/89 [00:36<01:31,  1.45s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 30%|███       | 27/89 [00:37<01:27,  1.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 31%|███▏      | 28/89 [00:38<01:24,  1.39s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 33%|███▎      | 29/89 [00:40<01:21,  1.37s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 34%|███▎      | 30/89 [00:41<01:19,  1.35s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 35%|███▍      | 31/89 [00:42<01:19,  1.37s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 36%|███▌      | 32/89 [00:44<01:18,  1.37s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 37%|███▋      | 33/89 [00:45<01:17,  1.38s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 38%|███▊      | 34/89 [00:47<01:18,  1.43s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 39%|███▉      | 35/89 [00:48<01:16,  1.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 40%|████      | 36/89 [00:49<01:13,  1.39s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 42%|████▏     | 37/89 [00:51<01:13,  1.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 43%|████▎     | 38/89 [00:52<01:13,  1.43s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 44%|████▍     | 39/89 [00:54<01:12,  1.45s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 45%|████▍     | 40/89 [00:55<01:12,  1.47s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 46%|████▌     | 41/89 [00:57<01:09,  1.45s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 47%|████▋     | 42/89 [00:58<01:06,  1.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 48%|████▊     | 43/89 [01:00<01:04,  1.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 49%|████▉     | 44/89 [01:01<01:02,  1.40s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 51%|█████     | 45/89 [01:02<01:01,  1.40s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 52%|█████▏    | 46/89 [01:04<01:00,  1.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 53%|█████▎    | 47/89 [01:05<00:59,  1.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 54%|█████▍    | 48/89 [01:07<00:58,  1.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 55%|█████▌    | 49/89 [01:08<00:56,  1.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 56%|█████▌    | 50/89 [01:09<00:54,  1.39s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 57%|█████▋    | 51/89 [01:11<00:52,  1.38s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 58%|█████▊    | 52/89 [01:12<00:50,  1.38s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 60%|█████▉    | 53/89 [01:14<00:51,  1.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 61%|██████    | 54/89 [01:15<00:48,  1.40s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 62%|██████▏   | 55/89 [01:16<00:48,  1.44s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 63%|██████▎   | 56/89 [01:18<00:46,  1.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 64%|██████▍   | 57/89 [01:19<00:45,  1.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 65%|██████▌   | 58/89 [01:21<00:43,  1.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 66%|██████▋   | 59/89 [01:22<00:42,  1.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 67%|██████▋   | 60/89 [01:24<00:40,  1.41s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 69%|██████▊   | 61/89 [01:25<00:40,  1.45s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 70%|██████▉   | 62/89 [01:27<00:39,  1.45s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 71%|███████   | 63/89 [01:28<00:36,  1.42s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 72%|███████▏  | 64/89 [01:29<00:34,  1.39s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 73%|███████▎  | 65/89 [01:31<00:33,  1.38s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 74%|███████▍  | 66/89 [01:32<00:31,  1.39s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
 75%|███████▌  | 67/89 [01:33<00:30,  1.37s/it]The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.

In [16]:
import pandas as pd

df = pd.DataFrame.from_dict(results, orient="index")
df.index.name = "dicom_id"
df.to_csv("results_with_report.csv")

df

,y_true,y_pred,image_files
dicom_id,,,
4a5bbca6-64ed6abf-84645068-6a7688bd-9a9910d4,1.0,1,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
7b43b8ff-190d3ca9-03cfbbd3-45ad3d0d-72d06c1c,1.0,1,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
463d2a28-b411bb98-f7bda38e-7030ebb9-74a8a1e0,0.0,0,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
a6a6000b-26fecffe-b90ded19-73b8a48f-6e3f7557,0.0,0,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
0cdfb937-27e0834d-4d8d1c40-cee9e187-98390c95,0.0,0,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
...,...,...,...
7f83f5d5-3afe2911-3b666b80-5dbde6e1-f2a9d980,0.0,0,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
6a7b83c9-7b7c6ba9-09d85de8-a76f1aa7-4fd0e047,1.0,1,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
54a9e5bc-2d3b9e9a-43c44b54-7c16e7b1-f923f86c,1.0,1,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
805c8f03-c6d068dd-c95f546c-e1dfe872-324866d0,1.0,1,/home/nicoleg/physionet.org/files/mimic-cxr-jp...
3ced14b8-2accf862-b2eab013-efdf4f2d-991f75eb,0.0,0,/home/nicoleg/physionet.org/files/mimic-cxr-jp...

In [17]:
y_true = df["y_true"].values
y_pred = df["y_pred"].values
target_names = [f"No {positive_class}", positive_class]


def generate_classification_report(
    y_true, y_pred, target_names=[f"No Pneumonia", "Pneumonia"]
):
    """
    Generate a classification report and confusion matrix.

    Parameters:
    -----------
    y_true : array-like
        True labels
    y_pred : array-like
        Predicted labels
    target_names : list
        List of class names

    Returns:
    --------
    cr : dict
        Classification report as a dictionary
    """
    from sklearn.metrics import classification_report, confusion_matrix
    from tabulate import tabulate

    # Classification report
    cr_string = classification_report(y_true, y_pred, target_names=target_names)
    cr = classification_report(
        y_true, y_pred, target_names=target_names, output_dict=True
    )
    print("Classification Report:")
    print(cr_string)

    # Confusion matrix
    print("Confusion Matrix:")
    cfm = confusion_matrix(y_true, y_pred)
    print(
        tabulate(
            cfm, headers=target_names, showindex=target_names, tablefmt="rounded_grid"
        )
    )
    return cr


cr = generate_classification_report(
    y_true,
    y_pred,
    target_names=target_names,
)

Classification Report:

              precision    recall  f1-score   support

No Pneumonia       0.95      0.93      0.94        59
   Pneumonia       0.87      0.90      0.89        30

    accuracy                           0.92        89
   macro avg       0.91      0.92      0.91        89
weighted avg       0.92      0.92      0.92        89

Confusion Matrix:

╭──────────────┬────────────────┬─────────────╮
│              │   No Pneumonia │   Pneumonia │
├──────────────┼────────────────┼─────────────┤
│ No Pneumonia │             55 │           4 │
├──────────────┼────────────────┼─────────────┤
│ Pneumonia    │              3 │          27 │
╰──────────────┴────────────────┴─────────────╯

In [18]:
summary = pd.DataFrame(
    {
        "f1-score": round(cr["macro avg"]["f1-score"], 4),
        # "roc auc": round(roc_auc_score(y_true, y_pred), 4),
        "sensitivity": round(cr["Pneumonia"]["recall"], 4),
        "specificity": round(cr["No Pneumonia"]["recall"], 4),
        "recall": round(cr["macro avg"]["recall"], 4),
        "precision": round(cr["macro avg"]["precision"], 4),
        "accuracy": round(cr["accuracy"], 4),
    },
    index=["chexagent"],
)
summary

           f1-score  sensitivity  specificity  recall  precision  accuracy
chexagent    0.9127          0.9       0.9322  0.9161     0.9096    0.9213